proyectoWeb/urls.py
from django.contrib import admin
from django.urls import path
from AppEquipos import views


from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/',views.generales,name="home"),
    path('detalles/<int:id>',views.detalles,name="detalles"),
    path('acer/',views.acer,name="acer"),
    path('apple/',views.apple,name="apple"),
    path('asus/',views.asus,name="asus"),
    path('compaq/',views.compaq,name="compaq"),
    path('dell/',views.dell,name="dell"),
    path('gateway/',views.gateway,name="gateway"),
    path('hp/',views.hp,name="hp"),
    path('huawei/',views.huawei,name="huawei"),
    path('lenovo/',views.lenovo,name="lenovo"),
    path('msi/',views.msi,name="msi"),
    path('samsung/',views.samsung,name="samsung"),
    path('sony/',views.sony,name="sony"),
    path('toshiba/',views.toshiba,name="toshiba"),
    path('documentacion/',views.documentacion,name="documentacion"),
    ]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

AppEquipos/models.py
from django.db import models

# Create your models here.


class PostMarcas(models.Model):
    title = models.CharField(max_length=255)
    def __str__(self):
        return self.title


class Post(models.Model):

    STATUS_CHOICES1={
         ('1','1'),
         ('2','2'),#ranuras
         ('3','3'),
         ('4','5'),
         ('rows of chips','Rows of chips')
    }

    STATUS_CHOICES2={
         ('2.5m','Mecanico 2.5'),
         ('3.5m','Mecanico 3.5'), #HDD
         ('especifica','SE ESPECIFICA EN NOTAS'),
         ('NO','NO')
    }
    STATUS_CHOICES3={
         ('1066 mHz','1066 MHz'),
         ('1200 mHz','1200 MHz'),
         ('1333 mHz','1333 MHz'),     #frecuencias mhz
         ('1600 mHz','1600 MHz'),
         ('1866 mHz','1866 MHz'),
         ('2000 mHz','2000 MHz'),
         ('2133 mHz','2133 MHz'),
         ('2400 mHz','2400 MHz'),
         ('2666 mHz','2666 MHz'),
         ('NO','NO')
    }
    STATUS_CHOICES4={
         ('m.2 sata','M.2 SATA'),
         ('2.5" sata','2.5" SATA'),
         ('m.2 pcie','M.2 PCIE'), #SSD
         ('especifica','SE ESPECIFICA EN NOTAS'),
         ('NO','NO')
    }

    marca= models.ForeignKey(PostMarcas,default=None,on_delete=models.CASCADE)
    modelo= models.CharField(max_length=45)
    ranuras=models.CharField(max_length=15,choices=STATUS_CHOICES1,default="ranuras")
    frecuencia=models.CharField(max_length=15,choices=STATUS_CHOICES3,default="frecuencia")
    SSD=models.CharField(max_length=20,choices=STATUS_CHOICES4,default="type_ssd")
    HDD=models.CharField(max_length=20,choices=STATUS_CHOICES2,default="type_hdd")
    notas=models.TextField()
    imagePortada= models.ImageField(null=True,blank=True)

    def __str__(self):
        return self.modelo

class Images(models.Model):
    post = models.ForeignKey(Post,on_delete=models.CASCADE)
    images = models.ImageField(upload_to='images/',blank=True,null=True)
    def __str__(self):
        return str(self.post.marca)

AppEquipos/views.py
from __future__ import unicode_literals
from django.shortcuts import render, HttpResponse, redirect, get_object_or_404
from .models import Post,PostMarcas,Images
# Create your views here.
from django.forms import modelformset_factory
from django.core.exceptions import ObjectDoesNotExist
from django.urls import reverse
from django.db.models import Q

def generales(request):
    query = request.GET.get('q')
    if query:
        post= Post.objects.filter(modelo__icontains = query)
    else:
        post= Post.objects.all()
    return render(request,"index.html",{'post':post,"query":query})

def acer(request):
    post=None
    error=None
    try:
        post = Post.objects.filter(
        marca=PostMarcas.objects.get(title="ACER")
        )
    except ObjectDoesNotExist as e:
        error=e
    return render(request,"marcas/acer.html",{"post":post,"error":error})
def apple(request):
    post=None
    error=None
    try:
        post = Post.objects.filter(
        marca=PostMarcas.objects.get(title="APPLE")
        )
    except ObjectDoesNotExist as e:
        error=e
    return render(request,"marcas/apple.html",{"post":post,"error":error})
def asus(request):
    error=None
    post=None
    try:
        post = Post.objects.filter(
        marca=PostMarcas.objects.get(title="ASUS")
        )
    except ObjectDoesNotExist as e:
        error=e
    return render(request,"marcas/asus.html",{"post":post,"error":error})
def compaq(request):
    error=None
    post = Post.objects.filter(
    marca=PostMarcas.objects.get(title="COMPAQ")
    )
    return render(request,"marcas/compaq.html",{"post":post})
def dell(request):
    error=None
    post=None
    try:
        post = Post.objects.filter(
        marca=PostMarcas.objects.get(title="DELL")
        )
    except ObjectDoesNotExist as e:
        error=e
    return render(request,"marcas/dell.html",{"post":post,"error":error})
def gateway(request):
    post=None
    error=None
    try:
        post = Post.objects.filter(
        marca=PostMarcas.objects.get(title="GATEWAY")
        )
    except ObjectDoesNotExist as e:
        error=e

    return render(request,"marcas/gateway.html",{"post":post,"error":error})
def hp(request):
    post=None
    error=None
    try:
        post = Post.objects.filter(
        marca=PostMarcas.objects.get(title="HP")
        )
    except ObjectDoesNotExist as e:
        error=e
    return render(request,"marcas/hp.html",{"post":post,"error":error})
def huawei(request):
    error=None
    post=None
    try:
        post = Post.objects.filter(
        marca=PostMarcas.objects.get(title="HUAWEI")
        )
    except ObjectDoesNotExist as e:
        error=e

    return render(request,"marcas/huawei.html",{"post":post,"error":error})
def lenovo(request):
    error=None
    post=None
    try:
        post = Post.objects.filter(
        marca=PostMarcas.objects.get(title="LENOVO")
        )
    except ObjectDoesNotExist as e:
        error=e
    return render(request,"marcas/lenovo.html",{"post":post,"error":error})
def msi(request):
    post=None
    error=None
    try:
        post = Post.objects.filter(
        marca=PostMarcas.objects.get(title="MSI")
        )
    except ObjectDoesNotExist as e:
        error=e

    return render(request,"marcas/msi.html",{"post":post,"error":error})
def samsung(request):
    post=None
    error=None
    try:
        post = Post.objects.filter(
        marca=PostMarcas.objects.get(title="SAMSUNG")
        )
    except ObjectDoesNotExist as e:
        error=e
    return render(request,"marcas/samsung.html",{"post":post,"error":error})
def sony(request):
    post=None
    error=None
    try:
        post = Post.objects.filter(
        marca=PostMarcas.objects.get(title="SONY")
        )
    except ObjectDoesNotExist as e:
        error=e
    return render(request,"marcas/sony.html",{"post":post,"error":error})
def toshiba(request):
    post=None
    error=None
    try:
        post = Post.objects.filter(
        marca=PostMarcas.objects.get(title="TOSHIBA")
        )
    except ObjectDoesNotExist as e:
        error=e
    return render(request,"marcas/toshiba.html",{"post":post,"error":error})

def detalles(request,id):
    detail= Post.objects.get(id=id)
    return render(request,"detalles.html",{'detail':detail})

def documentacion(request):
    return render(request,"blog/documentacion.html")

templates/blog/documentacion.html
{% extends 'index.html' %}
{% load static %}


{% block busqueda %}
{% endblock busqueda %}

{% block contenido %}
{% endblock contenido %}


{%block detalles%}
<div class="container">
    <div class="jumbotron">
    <div class="col-lg-12">
        <h1 class="font-weight-light title">Limites de Reparación y Servicios IMX</h1>
        <p class="card-text1">Equipos mojados, Equipos Rotos o dañados, Equipos viejos: Consultar con coordinador antes de ofrecer algún servicio al cliente.</p>
    </div>
    <div class="row align-items-center my-5">
      <div class="col-lg-12">
        <table class="table table-hover">
          <thead>
        <tr>
          <th scope="col">Servicios IMX</th>
          <th scope="col">Laptop <i class="fas fa-laptop"></i></th>
          <th scope="col">Escritorio <i class="fas fa-desktop"></i></th>
          <th scope="col">MacBook <i class="fab fa-apple"></i></th>
          <th scope="col">Imac <i class="fab fa-apple"></i></th>
        </tr>
      </thead>
      <tbody>
        <tr class="table-warning">
          <th scope="row">Reparación de pantalla TOUCH</th>
          <td><i class="fas fa-times"></i></td>
          <td><i class="fas fa-times"></i></td>
          <td><i class="fas fa-times"></i></td>
          <td><i class="fas fa-times"></i></td>
        </tr>
        <tr class="table-warning">
          <th scope="row">Cambio de pantallas con TOUCH</th>
          <td><i class="fas fa-times"></i></td>
          <td><i class="fas fa-times"></i></td>
          <td><i class="fas fa-times"></i></td>
          <td><i class="fas fa-times"></i></td>
        </tr>
        <tr class="table-success">
          <th scope="row">Cambio de pantalla sin TOUCH con número de parte</th>
          <td><i class="fas fa-check"></i></td>
          <td><i class="fas fa-check"></i></td>
          <td><i class="fas fa-check"></i></td>
          <td><i class="fas fa-check"></i></td>
        </tr>
        <tr class="table-warning">
          <th scope="row">Cambio de pantalla sin TOUCH sin número de parte</th>
          <td><i class="fas fa-times"></i></td>
          <td><i class="fas fa-times"></i></td>
          <td><i class="fas fa-times"></i></td>
          <td><i class="fas fa-times"></i></td>
        </tr>
        <tr class="table-warning">
          <th scope="row">Cambio o reparación de tarjeta madre</th>
          <td><i class="fas fa-times"></i></td>
          <td><i class="fas fa-times"></i></td>
          <td><i class="fas fa-times"></i></td>
          <td><i class="fas fa-times"></i></td>
        </tr>
        <tr class="table-warning">
          <th scope="row">Reparación de Jack de carga</th>
          <td><i class="fas fa-times"></i></td>
          <td><i class="fas fa-times"></i></td>
          <td><i class="fas fa-times"></i></td>
          <td><i class="fas fa-times"></i></td>
        </tr>
        <tr class="table-warning">
          <th scope="row">Cambio de Jack de carga soldado</th>
          <td><i class="fas fa-times"></i></td>
          <td><i class="fas fa-times"></i></td>
          <td><i class="fas fa-times"></i></td>
          <td><i class="fas fa-times"></i></td>
        </tr>
        <tr class="table-success">
          <th scope="row">(2) Cambio de Jack de carga con número de parte</th>
          <td><i class="fas fa-check"></i></td>
          <td><i class="fas fa-check"></i></td>
          <td><i class="fas fa-check"></i></td>
          <td><i class="fas fa-check"></i></td>
        </tr>
        <tr class="table-warning">
          <th scope="row">(2) Piezas internas sin número de parte</th>
          <td><i class="fas fa-times"></i></td>
          <td><i class="fas fa-times"></i></td>
          <td><i class="fas fa-times"></i></td>
          <td><i class="fas fa-times"></i></td>
        </tr>
        <tr class="table-success">
          <th scope="row">(2) Piezas internas con número de parte</th>
          <td><i class="fas fa-check"></i></td>
          <td><i class="fas fa-check"></i></td>
          <td><i class="fas fa-check"></i></td>
          <td><i class="fas fa-check"></i></td>
        </tr>
        <tr class="table-warning">
          <th scope="row">Mantenimiento interno físico a tipo Tablet</th>
          <td><i class="fas fa-times"></i></td>
          <td><i class="fas fa-times"></i></td>
          <td><i class="fas fa-times"></i></td>
          <td><i class="fas fa-times"></i></td>
        </tr>
        <tr class="table-warning">
          <th scope="row">Apertura de equipo con garantía por reparación</th>
          <td><i class="fas fa-times"></i></td>
          <td><i class="fas fa-times"></i></td>
          <td><i class="fas fa-times"></i></td>
          <td><i class="fas fa-times"></i></td>
        </tr>
        <tr class="table-warning">
          <th scope="row">Reballing</th>
          <td><i class="fas fa-times"></i></td>
          <td><i class="fas fa-times"></i></td>
          <td><i class="fas fa-times"></i></td>
          <td><i class="fas fa-times"></i></td>
        </tr>
        <tr class="table-warning">
          <th scope="row">Reparación Fisica Tablet y Celulares</th>
          <td><i class="fas fa-times"></i></td>
          <td><i class="fas fa-times"></i></td>
          <td><i class="fas fa-times"></i></td>
          <td><i class="fas fa-times"></i></td>
        </tr>

        <tr class="table-warning">
          <th scope="row">(1) Recuperación de información</th>
          <td><i class="fas fa-times"></i></td>
          <td><i class="fas fa-times"></i></td>
          <td><i class="fas fa-times"></i></td>
          <td><i class="fas fa-times"></i></td>
        </tr>
        <tr class="table-warning">
          <th scope="row">(1) Reparación o apertura de iMac delgadas 21" o 27"</th>
          <td><i class="fas fa-times"></i></td>
          <td><i class="fas fa-times"></i></td>
          <td><i class="fas fa-times"></i></td>
          <td><i class="fas fa-times"></i></td>
        </tr>
        <tr class="table-warning">
          <th scope="row">Cargador Asus sin información medidas puntas</th>
          <td><i class="fas fa-times"></i></td>
          <td><i class="fas fa-times"></i></td>
          <td><i class="fas fa-times"></i></td>
          <td><i class="fas fa-times"></i></td>
        </tr>
        <tr class="table-warning">
          <th scope="row">Casse equipos, carcasas o armazon</th>
          <td><i class="fas fa-times"></i></td>
          <td><i class="fas fa-times"></i></td>
          <td><i class="fas fa-times"></i></td>
          <td><i class="fas fa-times"></i></td>
        </tr>
        <tr class="table-warning">
          <th scope="row">Reparación SURFACE, Accesorios</th>
          <td><i class="fas fa-times"></i></td>
          <td><i class="fas fa-times"></i></td>
          <td><i class="fas fa-times"></i></td>
          <td><i class="fas fa-times"></i></td>
        </tr>
        <tr class="table-warning">
          <th scope="row">Licencias a la mano, sin instalación</th>
          <td><i class="fas fa-times"></i></td>
          <td><i class="fas fa-times"></i></td>
          <td><i class="fas fa-times"></i></td>
          <td><i class="fas fa-times"></i></td>
        </tr>


      </tbody>
    </table>

    </div>


</div>
{%endblock detalles%}

templates/detalles.html
{% extends 'index.html' %}
{% load static %}


{% block contenido %}
{% endblock contenido %}

{% block busqueda %}
<div class="row">
	<div class="col-lg-6">
		<h2 class="mb-2 ">  <i class="fa fa-laptop" aria-hidden="true"></i> {{detail.marca}} <span  class="span-cont"> {{detail.modelo}} </span> </h2>
	</div>
</div>
<div class="row">
	<div class="col-lg-4">
		<div class="service-item mb-5" data-aos="fade-left" >
			<i class="fas fa-memory"></i>
			<h4 class="my-3">Ranuras</h4>
				<p>{{detail.ranuras}}</p>
		</div>
	</div>
	<div class="col-lg-4">
		<div class="service-item mb-5" data-aos="fade-left"  data-aos-delay="450">
			<i class="fas fa-tachometer-alt"></i>
			<h4 class="my-3">Frecuencia/Velocdiad</h4>
			<p>{{detail.frecuencia}}</p>
		</div>
	</div>
	<div class="col-lg-4">
		<div class="service-item mb-5 mb-lg-0" data-aos="fade-left"  data-aos-delay="750">
			<i class="fa fa-hdd-o"></i>
			<h4 class="my-3">Tipo HDD</h4>
			<p>{{detail.HDD}}</p>
		</div>
	</div>
	<div class="col-lg-4">
		<div class="service-item" data-aos="fade-left"  data-aos-delay="750">
			<i class="fas fa-microchip"></i>
			<h4 class="my-3">Tipo SSD</h4>
			<p>{{detail.SSD}}</p>
		</div>
	</div>
	<div class="col-lg-4">
		<div class="service-item mb-5" data-aos="fade-left"  data-aos-delay="950">
			<i class="fas fa-clipboard"></i>
			<h4 class="my-3">Notas</h4>
			<p>{{detail.notas}}</p>
		</div>
	</div>

</div>
{% endblock busqueda %}

{%block detalles%}
<style>
.a-product__information--title {
    font-family: 'Baumans', cursive;
    color: #333;
    text-align-last: center;
}
section.o-product__detail {

    width: 100%;
    height: auto;
    min-height: 500px;
    box-shadow: 0 2px 4px 0 rgba(0,0,0,.1);
    display: flex;
    align-items: stretch;
}
section.o-product__detail>.container {
    display: grid;
    grid-template-columns: 7.5fr 2px 2.5fr;
    grid-template-rows: 1fr;
    padding: 0;
}
section.o-product__detail .o-product__description {
    padding: 6% 7%;
    width: 100%;
}
section.o-product__detail>.container main {
    display: grid;
    grid-template-columns: 60% 48%;
    grid-template-rows: 1fr;
    padding: 0;
    height: auto;
}
section.o-product__detail .o-product__description {
    padding: 6% 7%;
    width: 100%;
    background: #fff;
    height: fit-content;
    box-shadow: 0 8px 15px #0062cc;
    border-radius: 20px;
}
.span-cont{
color: #0043ffba;
}
.list-group-item {
    position: relative;
    display: flex;
    padding: .75rem 1.25rem;
    background-color: #fff;
    border: 1px solid rgba(0,0,0,.125);
}
.positionP{
    margin-top: 16px;
    margin-bottom: 1rem;
    font-size: 13px;
    font-family: 'Baumans', cursive;
}
</style>

<div class="container gallery-container">
                <div class="tz-gallery">
                {% if detail.images_set.all%}
                    <div class="row">
                       {% for d in detail.images_set.all %}
                        <div class="col-sm-6 col-md-4">
                            <a class="lightbox" href="{{d.images.url}}">
                                <img class="zoom"  src="{{d.images.url}}" alt="Park">
                            </a>
                        </div>
                        {% endfor %}
                    </div>

               {%else %}
                    <div class="alert alert-info">No hay imagenes documentadas aun!!</div>
                {%endif%}
                </div>
</div>
{%endblock detalles%}

templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="zxx">

<head>
  <meta charset="utf-8">
  <title>{% block title %}INICIO{% endblock title %}</title>

  <!-- mobile responsive meta -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

  <!--Font Awesomes Icons -->
    <link rel="stylesheet" href="{% static 'font-awesome/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'fontawesome-free-5.13.1-web/css/all.css' %}">

  <!-- ** Plugins Needed for the Project ** -->
  <!-- Bootstrap -->
  <link rel="stylesheet" href="{% static 'plugins/bootstrap/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'plugins/themify/css/themify-icons.css' %}">
  <link rel="stylesheet" href="{% static 'plugins/counto/animate.css' %}">
  <link rel="stylesheet" href="{% static 'plugins/aos/aos.css' %}">
  <link rel="stylesheet" href="{% static 'plugins/owl-carousel/owl.carousel.min.css' %}">
  <link rel="stylesheet" href="{% static 'plugins/owl-carousel/owl.theme.default.min.css' %}">
  <link rel="stylesheet" href="{% static 'plugins/magnific-popup/magnific-popup.css' %}">
  <link rel="stylesheet" href="{% static 'plugins/animated-text/animated-text.css' %}">

  <!-- Main Stylesheet -->
  <link href="{% static 'css/style.css' %}" rel="stylesheet">
  <link href="{% static 'css/gallery.css' %}" rel="stylesheet">

  <!--Gallery -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.8.1/baguetteBox.min.css">

</head>

<body>


<nav class="navbar navbar-expand-lg  main-nav " id="navbar">
	<div class="container">
	  <a class="navbar-brand" href="index.html">
	  	<img src="{% static 'logotipos/inte1.png' %}" alt="" >
	  </a>

	  <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarsExample09" aria-controls="navbarsExample09" aria-expanded="false" aria-label="Toggle navigation">
		<span class="ti-align-justify"></span>
	  </button>

		  <div class="collapse navbar-collapse" id="navbarsExample09">
			<ul class="navbar-nav ml-auto">
			  <li class="nav-item  active"><a class="nav-link" href="{% url 'home' %}">INICIO</a></li>

			  <li class="nav-item dropdown">
					<a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">FILTRAR +</a>
					<ul class="dropdown-menu" aria-labelledby="dropdown01">
						<li><a class="dropdown-item" href="{% url 'acer' %}">ACER</a></li>
						<li><a class="dropdown-item" href="{% url 'apple' %}">APPLE</a></li>
            <li><a class="dropdown-item" href="{% url 'asus' %}">ASUS</a></li>
            <li><a class="dropdown-item" href="{% url 'compaq' %}">COMPAQ</a></li>
            <li><a class="dropdown-item" href="{% url 'dell' %}">DELL</a></li>
            <li><a class="dropdown-item" href="{% url 'gateway' %}">GATEWAY</a></li>
            <li><a class="dropdown-item" href="{% url 'hp' %}">HP</a></li>
            <li><a class="dropdown-item" href="{% url 'huawei' %}">HUAWEI</a></li>
            <li><a class="dropdown-item" href="{% url 'lenovo' %}">LENOVO</a></li>
            <li><a class="dropdown-item" href="{% url 'msi' %}">MSI</a></li>
            <li><a class="dropdown-item" href="{% url 'samsung' %}">SAMSUNG</a></li>
            <li><a class="dropdown-item" href="{% url 'sony' %}">SONY</a></li>
            <li><a class="dropdown-item" href="{% url 'toshiba' %}">TOSHIBA</a></li>
					</ul>
			  </li>

			   <li class="nav-item"><a class="nav-link" href="{% url 'documentacion' %}">DOCUMENTACION</a></li>
			</ul>
		</div>
	</div>
</nav>


<section class="section banner">
	<div class="container">
    {% block busqueda %}
		<div class="row">
			<div class="col-lg-10">
				 <h2 class="cd-headline clip is-full-width mb-4 ">
				 	Equipos Documentados <br>
                    <span class="cd-words-wrapper text-color">
                        <b class="is-visible">HP</b>
                        <b>ACER</b>
                        <b>APPLE</b>
                        <b>LENOVO</b>
                        <b>TOSHIBA</b>
                        <b></b>
                    </span>
          </h2>
          <div>
          <form method="get">
            <div class="d-flex  h-100">
              <div class="searchbar">
                <input class="search_input" type="text" placeholder="Modelo" name="q">
                <a href="#" class="search_icon" type="submit"><i class="fas fa-search"></i></a>
              </div>
            </div>
          </form>
          <div>
		</div>
    {% endblock busqueda %}
	</div>
</section>

<!-- Banner End -->

<!-- POrtfolio start -->
{% block contenido %}
<section class="portfolio ">
	<div class="container">
    {% if post %}
		  <div class="row shuffle-wrapper portfolio-gallery">
              {% for p in post %}
      	      <div class="col-lg-4 col-6 mb-4 shuffle-item">
      	        <div class="position-relative inner-box" >
      	            <div class="image position-relative ">
                      <div class="card-body">
                      {{p.marca}}
                      {{p.modelo}}
                      </div>
      	               <img src="{{p.imagePortada.url}}" alt="portfolio-image" class="img-fluid w-100 d-block">
      	                <div class="overlay-box">
      	                  <div class="overlay-inner">
      		                    <a class="overlay-content" href="portfolio-single.html">
      		                      <h5 class="mb-0"><a href="{% url 'detalles' p.id %}">DETALLE</a></h5>
      		                    </a>
      	                	</div>
      		            </div>
      		        </div>
      		      </div>
      	      </div>
              {% endfor %}
      {% else %}
      <div class="alert alert-warning">
          <h4 class="alert-heading">NO HAY RESULTADOS PARA: <p>{{query}} </p></h4>
              <h5>No existe registro en la Base de Datos </h5>
          <hr>
          <h3 class="mb-0">Intenta de nuevo buscando otra Marca o Modelo</h3>
     </div>
      {%endif%}
	  </div>
	</div>
</section>
{% endblock contenido %}
<!-- Portfolio End-->

<!-- Service start -->

<section class="section service-home border-top">
	<div class="container">
    {%block detalles%}
    {%endblock detalles%}
	</div>
</section>

<!-- service end -->





<!-- Footer start -->

<section class="footer">
	<div class="container">
		<div class="row ">
			<div class="col-lg-6">
				<p class="mb-0">Copyrights © 2019. Designed & Developed by <a href="themefisher.com" class="text-white">Themefisher</a></p>
			</div>
			<div class="col-lg-6">
				<div class="widget footer-widget text-lg-right mt-5 mt-lg-0">
					<ul class="list-inline mb-0">
						<li class="list-inline-item"><a href="https://www.facebook.com/" target="_blank"><i class="ti-facebook mr-3"></i></a>
						</li>
						<li class="list-inline-item"><a href="https://twitter.com/" target="_blank"><i class="ti-twitter mr-3"></i></a>
						</li>
						<li class="list-inline-item"><a href="https://github.com/" target="_blank"><i class="ti-github mr-3"></i></a></li>
						<li class="list-inline-item"><a href="https://www.pinterest.com/" target="_blank"><i class="ti-pinterest mr-3"></i></a></li>
						<li class="list-inline-item"><a href="https://dribbble.com/" target="_blank"><i class="ti-dribbble mr-3"></i></a></li>
					</ul>
				</div>
			</div>
		</div>
	</div>
</section>

<!-- Footer End -->

<!-- jQuery -->
<script src="{% static 'plugins/jQuery/jquery.min.js' %}"></script>
<!-- Bootstrap JS -->
<script src="{% static 'plugins/bootstrap/bootstrap.min.js' %}"></script>
<script src="{% static 'plugins/aos/aos.js' %}"></script>
<script src="{% static 'plugins/owl-carousel/owl.carousel.min.js' %} "></script>
<script src="{% static 'plugins/shuffle/shuffle.min.js' %} "></script>
<script src="{% static 'plugins/magnific-popup/jquery.magnific-popup.min.js' %} "></script>
<script src="{% static 'plugins/animated-text/animated-text.js' %} "></script>
<script src="{% static 'plugins/counto/apear.js' %} "></script>
<script src="{% static 'plugins/counto/counTo.js' %}"></script>

 <!-- Google Map -->
<script src="{% static 'plugins/google-map/map.js' %}"></script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAkeLMlsiwzp6b3Gnaxd86lvakimwGA6UA&callback=initMap"></script>
<!-- Main Script -->
<script src="{% static 'js/script.js' %}"></script>



<!-- script Gallery -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.8.1/baguetteBox.min.js"></script>
<script>
          baguetteBox.run('.tz-gallery');
</script>
</html>

templates/marcas/acer.html
{% extends 'index.html' %}
{% load static %}
{% block title %} ACER {% endblock title %}